namespace JackAnalyzer.Parser
{
  public enum TokenType
  {
    KEYWORD,
    BOOLEAN, CHAR, CLASS, CONSTUCTOR, DO, ELSE, FALSE, FIELD, FUNCTION, IF, INT, LET, METHOD, NULL, RETURN, STATIC, THIS, TRUE, VAR, VOID, WHILE,

    SYMBOL,
    LEFT_BRACE, RIGHT_BRACE, LEFT_PAREN, RIGHT_PAREN, LEFT_BRACKET, RIGHT_BRACKET,
    COMMA, SEMICOLON, DOT,
    PLUS, MINUS, STAR, SLASH,
    LESS, LESS_THAN, LESS_EQUAL,
    GREATER, GREATER_THAN, GREATER_EQUAL,
    EQUAL, EQUAL_EQUAL,
    BANG, BANG_EQUAL,
    ESPERLUETTE, PIPE, TILDE,
    IDENTIFIER,
    INTEGER_CONSTANT,
    STRING_CONSTANT,
    EOF
  }
}